### ISSUE TITLE
Create configurable audio path and filename formatter

### ISSUE THREAD

**Issue by harlekoy** [luigel/laravel-text-to-speech#4]
Inside `config.php` we want the package to let user specify the default path of the audio and how it looks like. Below is how I imagine how it looks like in the `config` file.

```php
<?php

return [
    ...
        'audio' => [
        'path' => 'TTL',
        'formatter' => \Luigel\TextToSpeech\Formatters\DefaultFilenameFormatter::class,
    ],
    ...
];
```

Right now we have this in place which is totally okay but it would be great if the user can just override the default file path and the default file name.

``` php
/**
 * Ensures the path not to be null if it is null it will set a default path.
 *
 * @return void
 */
protected function ensurePathIsNotNull()
{
    $this->path = $this->path ?: '/TTS/'.now()->timestamp.config('tts.output_format');
}
```

> Note: inside the `DefaultFilenameFormatter` let's just have one method called `handle` which returns a filename without the audio format. Below is how it should look like if possible.

```
/**
 * Handles the filename of the audio.
 *
 * @param  string $text  The text source
 * @param  [type] $audio The result audio content.
 *
 * @return string
 */
public function handle($text, $audio)
{
    // e.g. user hash the `$text` or the `$audio` to generate the filename
}
```

**Comment by luigel** [comment]
Check this commit https://github.com/ci-on/laravel-text-to-speech/commit/c023b706b19c04a8c22578f1e3fc7f40a3ce57e6 for this issue. Thank you
