### ISSUE TITLE
Allow user to override or add more sources on the package.

### ISSUE THREAD

**Issue by harlekoy** [luigel/laravel-text-to-speech#5]
This is how should the `config.php` looks like on this feature.

```php
<?php

return [
    'default' => 'text',

    'sources' => [
        'text'    => \Luigel\TextToSpeech\Sources\TextSource::class,
        'path'    => \Luigel\TextToSpeech\Sources\PathSource::class,
        'website' => \Luigel\TextToSpeech\Sources\WebsiteSource::class,
    ],
    ...
```

and let's update how it should be implemented in the `Sourceable` trait.

In each of the source class, it should only have one method called `handle` and this is how it should look like if possible.

```php
/**
 * Handles in getting the text from source.
 *
 * @param  mixed $data
 * @return string
 */
public function handle ($data)
{
    //
}
```

**Comment by harlekoy** [comment]
The good thing with this feature the package user can have a more accurate source they can use as an example they will create a `MediumBlogSource` or `DevToBlogSource` which will be a great feature and it will come handy on there end.

**Comment by luigel** [comment]
Added this feature in this commit https://github.com/ci-on/laravel-text-to-speech/commit/be122b699e2312c0878bc155d675a9b9c441feb4
